workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-docker

pipeline:
  build:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - sh .drone.sh

  publish:
    image: plugins/docker
    repo: justinbarrick/docker
    tags: [ "latest", "17", "17.12" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    when:
      branch: master
      event: push

  publish:
    image: plugins/docker
    repo: justinbarrick/docker
    tags: [ "latest", "17", "17.12" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile.arm
    when:
      branch: master
      event: push

  publish:
    image: plugins/docker
    repo: justinbarrick/docker
    tags: [ "latest", "17", "17.12" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile.arm64
    when:
      branch: master
      event: push
