# docker build --rm -f docker/Dockerfile -t plugins/docker .

# docker:17.12.0-ce-dind arm
FROM docker@sha256:2e06a39653e557577c2ad5abf7eb3df80044b4c9b8918c2dbd09a48623e438fe

ADD release/linux/arm/drone-docker /bin/
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/drone-docker"]
