# docker build --rm -f docker/Dockerfile -t plugins/docker .

FROM docker:17.12.0-ce-dind@sha256:011a07ff036d1df1f2363f446228843dff36523676e04691b631124646841ab1

ADD release/linux/arm64/drone-docker /bin/
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/drone-docker"]
